# Prices for the shop
shop-prices:
  hopper: 1000
  end_crystal: 1000
  stone: 1.5
  gravel: 1.5
  dirt: 1.5
  cobblestone: 1
  sand: 2
  phantom: 100
  item_frame: 750
  shulker: 750

# Pay Message
# <player> is the player in the context (sender or receiver)
# <amount> is how much money is being exchanged
receiver-pay: "<blue><player> has sent you $<amount>"
sender-pay: "<blue><player> has received $<amount>"
usage-pay: "<blue>Correct usage: /pay <player> <amount>"
invalid-target: "<player> does not exist or is offline"
insufficient-funds: "You do not have enough funds to carry out the transaction"

redis-url: "redis://localhost"
