# Connection Configuration
host: ""
port: ""
database: ""
username: ""
password: ""

# Prices for the shop
shop-prices:
  hopper: 1000
  end_crystal: 1000
  stone: 1.5
  gravel: 1.5
  dirt: 1.5
  cobblestone: 1
  sand: 2
  phantom: 100
  item_frame: 750
  shulker: 750

# Prices for the jobs
actions:
  - kill
  - smelt
  - craft
  - break
  - place
  - breed
  - shear
  - milk
  - fish

action-material-mapping:
  kill: "diamond_sword"
  smelt: "furnace"
  craft: "crafting_table"
  break: "diamond_pickaxe"
  place: "diamond_axe"
  breed: "wheat"
  shear: "shears"
  milk: "milk_bucket"
