# This is a basic workflow to help you get started with Actions
name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install LFTP
        run: sudo apt install lftp -y

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          cache: 'maven'
          distribution: 'zulu'

      - name: Build Project
        run: mvn -B package -f pom.xml
      
      - name: Upload JAR to Server
        run: |
          lftp --env-password $SERVER_FTP_LINK -e "cd plugins; put target/eoncurrency-1.0.jar; bye"
        env:
          SERVER_FTP_LINK: ${{ secrets.SERVER_FTP_LINK }}
          LFTP_PASSWORD: ${{ secrets.LFTP_PASSWORD }}
